// Copyright 2025. All Rights Reserved.
// Generated by TableSubsystemGenerator.py. DO NOT EDIT.

#include "RoomEscapeFPS//Public/Subsystems/TableSubsystem.h"
#include "AssetRegistry/AssetRegistryModule.h"
#include "Engine/DataTable.h"

void UTableSubsystem::Initialize(FSubsystemCollectionBase& Collection)
{
    Super::Initialize(Collection);
    LoadAllTables();
}

void UTableSubsystem::Deinitialize()
{
    LoadedTables.Empty();
    Super::Deinitialize();
}

void UTableSubsystem::LoadAllTables()
{
    FAssetRegistryModule& AssetRegistryModule = FModuleManager::LoadModuleChecked<FAssetRegistryModule>(TEXT("AssetRegistry"));
    TArray<FAssetData> AssetData;

    FARFilter Filter;
    Filter.PackagePaths.Add(TEXT("/Game/Tables/"));
    Filter.ClassPaths.Add(UDataTable::StaticClass()->GetClassPathName());

    AssetRegistryModule.Get().GetAssets(Filter, AssetData);

    for (const FAssetData& Data : AssetData)
    {
        UDataTable* LoadedTable = Cast<UDataTable>(Data.GetAsset());
        if (LoadedTable && LoadedTable->RowStruct)
        {
            LoadedTables.Add(LoadedTable->RowStruct, LoadedTable);
        }
    }
    UE_LOG(LogTemp, Log, TEXT("UTableSubsystem: Loaded %d data tables from %s"), LoadedTables.Num(), TEXT("/Game/Tables/"));
}

// ~~~ Generated Function Implementations ~~~
FTableSkillRow const* UTableSubsystem::GetSkillRow(FSkillNo const& RowName) const { return GetData<FSkillNo, FTableSkillRow>(RowName); }
TMap<FSkillNo, FTableSkillRow*> const& UTableSubsystem::GetAllSkillRow() { return GetMap(CachedSkillRowMap); }
FTableTestRow const* UTableSubsystem::GetTestRow(FTestNo const& RowName) const { return GetData<FTestNo, FTableTestRow>(RowName); }
TMap<FTestNo, FTableTestRow*> const& UTableSubsystem::GetAllTestRow() { return GetMap(CachedTestRowMap); }
FTableTest2Row const* UTableSubsystem::GetTest2Row(FTest2No const& RowName) const { return GetData<FTest2No, FTableTest2Row>(RowName); }
TMap<FTest2No, FTableTest2Row*> const& UTableSubsystem::GetAllTest2Row() { return GetMap(CachedTest2RowMap); }
