// Copyright 2025. All Rights Reserved.
// Generated by TableSubsystemGenerator.py. DO NOT EDIT.

#pragma once

#include "CoreMinimal.h"
#include "Subsystems/GameInstanceSubsystem.h"
#include "Globals/g_struct.h"
#include "TableSubsystem.generated.h"

UCLASS()
class ROOMESCAPEFPS_API UTableSubsystem : public UGameInstanceSubsystem
{
    GENERATED_BODY()

public:
    void Initialize(FSubsystemCollectionBase& Collection) override;
    void Deinitialize() override;

    // ~~~ Generated Public Getters ~~~
    [[nodiscard]] FTableSkillRow const* GetSkillRow(FSkillNo const& RowName) const;
    [[nodiscard]] FTableTestRow const* GetTestRow(FTestNo const& RowName) const;
    [[nodiscard]] FTableTest2Row const* GetTest2Row(FTest2No const& RowName) const;

    // ~~~ Generated Public GetAll Functions ~~~
    TMap<FSkillNo, FTableSkillRow*> const& GetAllSkillRow();
    TMap<FTestNo, FTableTestRow*> const& GetAllTestRow();
    TMap<FTest2No, FTableTest2Row*> const& GetAllTest2Row();

private:
    void LoadAllTables();

    template <typename TKeyType, typename TRowType>
    TRowType const* GetData(TKeyType const& RowName) const
    {
        if (auto const* TablePtr = LoadedTables.Find(TRowType::StaticStruct()))
        {
            TCHAR TempBuffer[16];
            FCString::Sprintf(TempBuffer, TEXT("%d"), RowName._value);
            return (*TablePtr)->template FindRow<TRowType>(FName(TempBuffer), TEXT(""));
        }
        return nullptr;
    }
    
    template <typename TKeyType, typename TRowType>
    TMap<TKeyType, TRowType*> const& GetMap(TMap<TKeyType, TRowType*>& outMap)
    {
        if (outMap.IsEmpty())
        {
            if (auto const* TablePtr = LoadedTables.Find(TRowType::StaticStruct()))
            {
                auto const& RowMap = (*TablePtr)->GetRowMap();
                outMap.Reserve(RowMap.Num());
                for (auto const& [Key, Value] : RowMap)
                {
                    outMap.Emplace(TKeyType(FCString::Atoi(*Key.ToString())), reinterpret_cast<TRowType*>(Value));
                }
            }
        }
        return outMap;
    }
    
    UPROPERTY()
    TMap<TObjectPtr<UScriptStruct>, TObjectPtr<UDataTable>> LoadedTables;
    
    // ~~~ Generated Cached Maps for GetMap ~~~
    TMap<FSkillNo, FTableSkillRow*> CachedSkillRowMap;
    TMap<FTestNo, FTableTestRow*> CachedTestRowMap;
    TMap<FTest2No, FTableTest2Row*> CachedTest2RowMap;
};
