import os
import re

# -----------------------------------------------------------------------------
# 1. 설정: 구조체 헤더 파일 경로와 데이터 테이블 애셋 폴더 경로
# -----------------------------------------------------------------------------
STRUCT_HEADER_PATH = "D:/RoomEscapeFPS/Source/RoomEscapeFPS/Public/Globals/g_struct.h"
DATATABLE_ASSET_DIRECTORY = "/Game/Tables/"

# -----------------------------------------------------------------------------
# 2. C++ 코드 템플릿
# -----------------------------------------------------------------------------
H_TEMPLATE = """// Copyright 2025. All Rights Reserved.
// Generated by TableSubsystemGenerator.py. DO NOT EDIT.

#pragma once

#include "CoreMinimal.h"
#include "Subsystems/GameInstanceSubsystem.h"
#include "Globals/g_struct.h"
#include "TableSubsystem.generated.h"

UCLASS()
class ROOMESCAPEFPS_API UTableSubsystem : public UGameInstanceSubsystem
{{
    GENERATED_BODY()

public:
    void Initialize(FSubsystemCollectionBase& Collection) override;
    void Deinitialize() override;

    // ~~~ Generated Public Getters ~~~
{public_getters}

    // ~~~ Generated Public GetAll Functions ~~~
{public_getall_functions}

private:
    void LoadAllTables();

    template <typename TKeyType, typename TRowType>
    TRowType const* GetData(TKeyType const& RowName) const
    {{
        if (auto const* TablePtr = LoadedTables.Find(TRowType::StaticStruct()))
        {{
            TCHAR TempBuffer[16];
            FCString::Sprintf(TempBuffer, TEXT("%d"), RowName._value);
            return (*TablePtr)->template FindRow<TRowType>(FName(TempBuffer), TEXT(""));
        }}
        return nullptr;
    }}
    
    template <typename TKeyType, typename TRowType>
    TMap<TKeyType, TRowType*> const& GetMap(TMap<TKeyType, TRowType*>& outMap)
    {{
        if (outMap.IsEmpty())
        {{
            if (auto const* TablePtr = LoadedTables.Find(TRowType::StaticStruct()))
            {{
                auto const& RowMap = (*TablePtr)->GetRowMap();
                outMap.Reserve(RowMap.Num());
                for (auto const& [Key, Value] : RowMap)
                {{
                    outMap.Emplace(TKeyType(FCString::Atoi(*Key.ToString())), reinterpret_cast<TRowType*>(Value));
                }}
            }}
        }}
        return outMap;
    }}
    
    UPROPERTY()
    TMap<TObjectPtr<UScriptStruct>, TObjectPtr<UDataTable>> LoadedTables;
    
    // ~~~ Generated Cached Maps for GetMap ~~~
{cached_maps}
}};
"""

CPP_TEMPLATE = """// Copyright 2025. All Rights Reserved.
// Generated by TableSubsystemGenerator.py. DO NOT EDIT.

#include "TableSubsystem.h"
#include "AssetRegistry/AssetRegistryModule.h"
#include "Engine/DataTable.h"

void UTableSubsystem::Initialize(FSubsystemCollectionBase& Collection)
{{
    Super::Initialize(Collection);
    LoadAllTables();
}}

void UTableSubsystem::Deinitialize()
{{
    LoadedTables.Empty();
    Super::Deinitialize();
}}

void UTableSubsystem::LoadAllTables()
{{
    FAssetRegistryModule& AssetRegistryModule = FModuleManager::LoadModuleChecked<FAssetRegistryModule>(TEXT("AssetRegistry"));
    TArray<FAssetData> AssetData;

    FARFilter Filter;
    Filter.PackagePaths.Add(TEXT("{datatable_dir}"));
    Filter.ClassPaths.Add(UDataTable::StaticClass()->GetClassPathName());

    AssetRegistryModule.Get().GetAssets(Filter, AssetData);

    for (const FAssetData& Data : AssetData)
    {{
        UDataTable* LoadedTable = Cast<UDataTable>(Data.GetAsset());
        if (LoadedTable && LoadedTable->RowStruct)
        {{
            LoadedTables.Add(LoadedTable->RowStruct, LoadedTable);
        }}
    }}
    UE_LOG(LogTemp, Log, TEXT("UTableSubsystem: Loaded %d data tables from %s"), LoadedTables.Num(), TEXT("{datatable_dir}"));
}}

// ~~~ Generated Function Implementations ~~~
{function_implementations}
"""

# -----------------------------------------------------------------------------
# 3. 코드 생성 로직
# -----------------------------------------------------------------------------
def generate_code():
    public_getters = []
    public_getall_functions = []
    cached_maps = []
    function_implementations = []

    try:
        with open(STRUCT_HEADER_PATH, 'r', encoding='utf-8') as f:
            content = f.read()
    except FileNotFoundError:
        print(f"Error: Struct header file not found at '{STRUCT_HEADER_PATH}'")
        return

    # FTableRowBase를 상속받는 USTRUCT를 정규식으로 찾기: USTRUCT(BlueprintType) struct XXX final : public FTableRowBase
    struct_matches = re.findall(
    r"USTRUCT\(.*?\)\s*struct\s+(?:\w+_API\s+)?(F\w+)(?:\s+final)?\s*:\s*public\s+FTableRowBase",
    content,
    re.DOTALL)
    
    if not struct_matches:
        print(f"No structs inheriting from FTableRowBase found in '{STRUCT_HEADER_PATH}'.")
        return

    for struct_name in struct_matches:
        base_name = struct_name[6:] # 'FTable' 접두사 제거
        temp_string = struct_name.replace("FTable", "F") 
        row_no_string = temp_string.replace("Row", "No")

        # Getters
        public_getters.append(f"    [[nodiscard]] {struct_name} const* Get{base_name}({row_no_string} const& RowName) const;")
        
        # GetAll Functions
        public_getall_functions.append(f"    TMap<{row_no_string}, {struct_name}*> const& GetAll{base_name}();")

        # Cached Maps
        cached_maps.append(f"    TMap<{row_no_string}, {struct_name}*> Cached{base_name}Map;")
        
        # Function Implementations
        function_implementations.append(f"{struct_name} const* UTableSubsystem::Get{base_name}({row_no_string} const& RowName) const {{ return GetData<{row_no_string}, {struct_name}>(RowName); }}")
        function_implementations.append(f"TMap<{row_no_string}, {struct_name}*> const& UTableSubsystem::GetAll{base_name}() {{ return GetMap(Cached{base_name}Map); }}")

    struct_header_filename = os.path.basename(STRUCT_HEADER_PATH)
    
    # 템플릿 채우기
    h_content = H_TEMPLATE.format(
        public_getters='\n'.join(public_getters),
        public_getall_functions='\n'.join(public_getall_functions),
        cached_maps='\n'.join(cached_maps),
        struct_header_filename=struct_header_filename
    )
    cpp_content = CPP_TEMPLATE.format(
        function_implementations='\n'.join(function_implementations),
        datatable_dir=DATATABLE_ASSET_DIRECTORY
    )

    # 파일로 저장
    output_dir_public = "D:/RoomEscapeFPS/Source/RoomEscapeFPS/Public/Subsystems"
    output_dir_private = "D:/RoomEscapeFPS/Source/RoomEscapeFPS/Private/Subsystems"
    os.makedirs(output_dir_public, exist_ok=True)
    os.makedirs(output_dir_private, exist_ok=True)
    with open(os.path.join(output_dir_public, "TableSubsystem.h"), "w", encoding="utf-8") as f:
        f.write(h_content)
    with open(os.path.join(output_dir_private, "TableSubsystem.cpp"), "w", encoding="utf-8") as f:
        f.write(cpp_content)

    print(f"Successfully generated advanced TableSubsystem in '{output_dir_public}' and '{output_dir_private}' folders.")
    print(f"Found and generated for {len(struct_matches)} structs: {', '.join(struct_matches)}")


if __name__ == "__main__":
    generate_code()