import yaml
import os
import sys

# Configuration
DEFAULT_YAML_PATH = "D:/RoomEscapeFPS/Yaml/enum.yaml"  # Default YAML file path
OUTPUT_HEADER_PATH = "D:/RoomEscapeFPS/Source/RoomEscapeFPS/Public/Globals/g_enum.h"  # Output header file path

def generate_enum_header(yaml_file, output_file):
    # Read YAML file
    with open(yaml_file, 'r') as f:
        data = yaml.safe_load(f)
    
    # Generate header content
    header_content = """// Generated by enum_generator.py
#pragma once

"""
    
    # Process each enum
    for enum in data['enums']:
        enum_name = 'E' + enum['name']
        entries = [entry.upper() for entry in enum['entries']]
        
        # Add UENUM macro
        header_content += f"UENUM(BlueprintType)\n"
        header_content += f"enum class {enum_name} : uint8\n"
        header_content += "{\n"
        
        # Add NONE as first entry
        header_content += f"\tNONE = 0 UMETA(Hidden),\n"
        
        # Add all entries
        for entry in entries:
            header_content += f"\t{entry},\n"
        
        # Add MAX as last entry
        header_content += f"\tMAX UMETA(Hidden)\n"
        header_content += "};\n\n"
    
    # Write to output file
    with open(output_file, 'w') as f:
        f.write(header_content)

if __name__ == "__main__":
    # Get YAML path from command line argument or use default
    yaml_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_YAML_PATH
    generate_enum_header(yaml_path, OUTPUT_HEADER_PATH)
